
import { GoogleGenAI } from "@google/genai";

// This instance is for non-Veo models like Imagen
const genAI = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

export async function generateLogoImage(prompt: string): Promise<string> {
    try {
        const response = await genAI.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/jpeg',
              aspectRatio: '1:1',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return base64ImageBytes;
        } else {
            throw new Error('No images were generated by the API.');
        }

    } catch (error) {
        console.error('Error generating logo image:', error);
        throw new Error('Failed to communicate with the image generation API.');
    }
}


export async function generateLogoVideo(
    prompt: string, 
    imageBase64: string,
    aspectRatio: '16:9' | '9:16'
): Promise<string> {
    // For Veo models, create a new instance just-in-time to ensure the latest selected API key is used.
    const veoGenAI = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

    try {
        let operation = await veoGenAI.models.generateVideos({
            model: 'veo-3.1-fast-generate-preview',
            prompt: prompt,
            image: {
                imageBytes: imageBase64,
                mimeType: 'image/jpeg', // Assuming jpeg, could be png
            },
            config: {
                numberOfVideos: 1,
                resolution: '720p',
                aspectRatio: aspectRatio,
            }
        });

        // Polling for the result
        while (!operation.done) {
            await new Promise(resolve => setTimeout(resolve, 10000)); // Wait for 10 seconds before polling again
            operation = await veoGenAI.operations.getVideosOperation({ operation: operation });
        }

        if (operation.response?.generatedVideos && operation.response.generatedVideos.length > 0) {
            const downloadLink = operation.response.generatedVideos[0].video?.uri;
            if (!downloadLink) {
                throw new Error('Video generation completed, but no download link was provided.');
            }
            
            // The downloadLink requires the API key to be appended for access
            const videoResponse = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
            if (!videoResponse.ok) {
                throw new Error(`Failed to download the generated video. Status: ${videoResponse.statusText}`);
            }
            
            const videoBlob = await videoResponse.blob();
            return URL.createObjectURL(videoBlob);
        } else {
             throw new Error('Video generation operation did not return any videos.');
        }

    } catch (error: any) {
        console.error('Error generating logo video:', error);
        // Pass the error message up to the UI component for better user feedback
        throw new Error(error.message || 'An unknown error occurred during video generation.');
    }
}
